twist_mux:
  ros__parameters:
    use_stamped: false  # Set to true if using geometry_msgs/TwistStamped
    topics:
      keyboard:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      keyboard_manual:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 20
      nav2_controller:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 30
      nav2_velocity_smoother:
        topic   : cmd_vel_smoothed
        timeout : 0.5
        priority: 40
      # tracker:
      #   topic   : cmd_vel_tracker
      #   timeout : 0.5
      #   priority: 50